name: CI/CD Pipeline - Desafio Credito

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and Test credito-api
      working-directory: ./credito-api
      run: |
        mvn clean package -DskipTests
        mvn test

  build-and-test-auditoria:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and Test credito-auditoria
      working-directory: ./credito-auditoria
      run: |
        mvn clean package -DskipTests
        mvn test

  build-and-test-notificacoes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and Test credito-notificacoes
      working-directory: ./credito-notificacoes
      run: |
        mvn clean package -DskipTests
        mvn test

  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'
        cache: 'npm'
        cache-dependency-path: ./credito-frontend/package-lock.json
    - name: Build credito-frontend
      working-directory: ./credito-frontend
      run: |
        npm install
        npm run build --prod

  build-and-test-analitico:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Build credito-analitico
      working-directory: ./credito-analitico
      run: |
        pip install -r requirements.txt

  build-and-push-docker:
    needs:
      - build-and-test-api
      - build-and-test-auditoria
      - build-and-test-notificacoes
      - build-and-test-frontend
      - build-and-test-analitico
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/credito-api:latest ./credito-api
        docker build -t ${{ secrets.DOCKER_USERNAME }}/credito-auditoria:latest ./credito-auditoria
        docker build -t ${{ secrets.DOCKER_USERNAME }}/credito-notificacoes:latest ./credito-notificacoes
        docker build -t ${{ secrets.DOCKER_USERNAME }}/credito-frontend:latest ./credito-frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/credito-analitico:latest ./credito-analitico
        docker push ${{ secrets.DOCKER_USERNAME }}/credito-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/credito-auditoria:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/credito-notificacoes:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/credito-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/credito-analitico:latest