services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: credito_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]
    networks:
      - app-network
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:909掳
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 4
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network
  api:
    image: ${DOCKER_USERNAME}/credito-api:latest
    build:
      context: ./api/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/credito_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - app-network
    # Instala o postgresql-client para usar pg_isready
    command: ["/bin/sh", "-c", "apt-get update && apt-get install -y postgresql-client && /app/wait-for-db.sh"]
  auditoria:
    image: ${DOCKER_USERNAME}/credito-auditoria:latest
    build:
      context: ./auditoria/auditoria
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/credito_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - app-network
  notificacoes:
    image: ${DOCKER_USERNAME}/credito-notificacoes:latest
    build:
      context: ./notificacoes/notificacoes
      dockerfile: Dockerfile
    depends_on:
      - db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/credito_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - app-network
    command: ["/bin/sh", "-c", "apt-get update && apt-get install -y postgresql-client && /app/wait-for-db.sh"]
volumes:
  postgres_data:
  mongo_data:
networks:
  app-network:
    driver: bridge